name: Blackduck

on:
  workflow_dispatch:
  # schedule: nightly

jobs:
  blackduck:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: maven
      - run: echo foo
