name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.color=false -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MVN_CLI_ARGS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

jobs:

  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - run: mvn $MVN_CLI_ARGS net.revelc.code.formatter:formatter-maven-plugin:2.22.0:validate

  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - name: Build with Maven
        run: mvn $MVN_CLI_ARGS -DskipTests install -X
      - run: mvn dependency:list -Dsort=true

      # Stash target so we can avoid the need to recompile in later jobs
      - uses: actions/upload-artifact@v3
        with:
          name: target
          path: target

  archetype-tests:
    name: Test Archetype ${{ matrix.archetype }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        archetype:
          - "scp-cf-tomee"
          - "scp-cf-spring"
          # - "scp-cf-spring-jakarta"
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
          
      - name: Generate Project from Archetype ${{matrix.archetype}}
        run:  mvn $MVN_CLI_ARGS archetype:generate -DarchetypeGroupId=com.sap.cloud.sdk.archetypes -DarchetypeArtifactId=${{matrix.archetype}} -DarchetypeVersion=4.12.0 -DgroupId=com.sap.test -DartifactId=example-${{matrix.archetype}} -Dversion=1.0-SNAPSHOT -Dpackage=com.sap.test -Dhttp.keepAlive=false
        working-directory: /home/runner/work/_temp
      - name: Build Project based on Archetype ${{matrix.archetype}}
        run: mvn $MVN_CLI_ARGS verify
        working-directory: /home/runner/work/_temp/example-${{matrix.archetype}}

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - name: Build with Maven
        run: mvn $MVN_CLI_ARGS test -X
      - run: mvn dependency:list -Dsort=true

  copyright-header-check:
    name: Open Source Compliance Check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - run: echo foo

  static-code-checks:
    name: Static Code Checks
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - run: echo foo

  deploy-snapshot:
    name: Deploy Snapshot
    runs-on: ubuntu-latest
    needs:
      - build
      - archetype-tests
      - tests
      - copyright-header-check
      - static-code-checks
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - run: echo foo
