name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '17' ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven
        run: mvn install

  # q: do we need upload artifact or is the maven cache enough to get all we need?
  archetype-tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        archetype: [ 'scp-cf-tomee', 'scp-cf-spring', 'scp-cf-spring-jakarta', 'scp-neo-javaee7' ]
    name: Java ${{ matrix.ararchetype }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven
      - name: Build with Maven
        run: echo mvn archetype generate  ${{ matrix.ararchetype }}

      - run: find . -name demo-0.0.1-SNAPSHOT.jar
