name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  MAVEN_OPTS: "-Dmaven.repo.local=local_maven_repo/ -Dhttps.protocols=TLSv1.2 -Dmaven.color=false"
  MVN_CLI_ARGS: "--batch-mode --no-transfer-progress --errors --fail-at-end --show-version"

jobs:

  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - run: mvn $MVN_CLI_ARGS net.revelc.code.formatter:formatter-maven-plugin:2.22.0:validate

  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      # - run: mkdir -p local_maven_repo
      - name: Build with Maven
        run: mvn $MVN_CLI_ARGS -DskipTests install

      # Stash target so we can avoid the need to recompile in later jobs
      - name: Stash compiled classes
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target
          retention-days: '1'
      - name: Stash local maven repo
        uses: actions/upload-artifact@v3
        with:
          name: local_maven_repo
          path: local_maven_repo
          retention-days: '1'
      - run: ls -l --time-style=full-iso target
      - run: find ~/.m2 -name spring-boot-starter-web-3.0.6.jar
      - run: find local_maven_repo -name spring-boot-starter-web-3.0.6.jar

  archetype-tests:
    name: Test Archetype ${{ matrix.archetype }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        archetype:
          - "scp-cf-tomee"
          - "scp-cf-spring"
          # - "scp-cf-spring-jakarta"
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
          
      - name: Generate Project from Archetype ${{matrix.archetype}}
        run:  mvn $MVN_CLI_ARGS archetype:generate -DarchetypeGroupId=com.sap.cloud.sdk.archetypes -DarchetypeArtifactId=${{matrix.archetype}} -DarchetypeVersion=4.12.0 -DgroupId=com.sap.test -DartifactId=example-${{matrix.archetype}} -Dversion=1.0-SNAPSHOT -Dpackage=com.sap.test -Dhttp.keepAlive=false
        working-directory: /home/runner/work/_temp
      - name: Build Project based on Archetype ${{matrix.archetype}}
        run: mvn $MVN_CLI_ARGS verify
        working-directory: /home/runner/work/_temp/example-${{matrix.archetype}}

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - name: Download compiled classes
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: Download local maven repo
        uses: actions/download-artifact@v3
        with:
          name: local_maven_repo
          path: local_maven_repo
      - run: ls -l --time-style=full-iso target

      - name: Build with Maven
        run: mvn $MVN_CLI_ARGS test -X
      - run: find ~/.m2 -name spring-boot-starter-web-3.0.6.jar
      - run: find local_maven_repo -name spring-boot-starter-web-3.0.6.jar

      - run: mvn $MVN_CLI_ARGS dependency:list -Dsort=true

  copyright-header-check:
    name: Open Source Compliance Check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - run: echo foo

  static-code-checks:
    name: Static Code Checks
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - name: Download compiled classes
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: Download local maven repo
        uses: actions/download-artifact@v3
        with:
          name: local_maven_repo
          path: local_maven_repo
      - run: echo foo

  deploy-snapshot:
    name: Deploy Snapshot
    runs-on: ubuntu-latest
    needs:
      - build
      - archetype-tests
      - tests
      - copyright-header-check
      - static-code-checks
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - name: Download compiled classes
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: Download local maven repo
        uses: actions/download-artifact@v3
        with:
          name: local_maven_repo
          path: local_maven_repo
      - run: echo foo
